language: node_js
node_js:
  - '18'
services:
  - mongodb
cache: npm
branches:
  only:
    - main
env:
  global:
    - PORT=3000
    - MONGODB_URL=mongodb://localhost:27017/flight-management
script:
  - npm install
  - npm run lint
  - npm run test
after_success: npm coverage:coveralls